networkGateway: "kube-network"
# service:
#   ports:
#     - name: hbone
#       port: 15008
#       targetPort: 15008
#       protocol: TCP
#       appProtocol: hbone
# service:
#   ports:
#     - name: status-port
#       port: 15021
#       targetPort: 15021
#     - name: tls
#       port: 15443
#       targetPort: 15443
#     - name: tls-istiod
#       port: 15012
#       targetPort: 15012
#     - name: tls-webhook
#       port: 15017
#       targetPort: 15017
