{{- if .Values.gateway.enabled }}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
  {{- if .Values.gateway.labels }}
  labels:
  {{ .Values.gateway.labels | toYaml | nindent 6 }}
  {{- end }}
spec:
  selector:
    {{ .Values.gateway.selector | toYaml }}
  servers:
    {{- range $server := .Values.gateway.servers }}
    - {{- $server | toYaml | nindent 6 }}
    {{- end }}
{{- end }}
