{{- if .Values.gatewayv2.enabled }}
{{- range .Values.gatewayv2.gateways  }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  {{- if .labels }}
  labels:
  {{ .labels | toYaml | nindent 6 }}
  {{- end }}
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  gatewayClassName: {{ .gatewayclass }}
  listeners:
  {{- range $listener := .listeners }}
  - {{- $listener | toYaml | nindent 6 }}
  {{- end}}
{{- end }}
{{- end }}
