{{ range $name,$group := .Values.workloadGroups }}
apiVersion: networking.istio.io/v1
kind: WorkloadGroup
metadata:
  name: {{ $name }}
  namespace: {{ $group.namespace }}
spec:
  metadata:
    labels:
      {{- toYaml $group.labels | nindent 6 }}
  template:
    serviceAccount: {{ $group.serviceAccount }}
    {{- if $group.network }}
    network: {{ $group.network }}
    {{- end }}

{{ end }}
