proxmox_api_url      = "https://pve1.lobster.icu:8006/api2/json"
proxmox_insecure_url = true
proxmox_node         = "pve1"
base_template_name   = "ubuntu-2504-base-0.0.2"
template_name        = "ubuntu-2504-docker-registry"
vm_name              = "docker-registry"
starting_vm_id       = 1004
template_version     = "0.0.2"
template_description = "An Ubuntu 25.04 image with docker installed"
